# This is a basic test macro
# It should be updated only to retain basic RAT/G4 command syntax

/PhysicsList/OmitMuonicProcesses true
/PhysicsList/OmitHadronicProcesses true

/run/initialize
##########EVENT LOOP############
/rat/proc frontend
/rat/proc trigger
/rat/proc eventbuilder
/rat/proc calibratePMT

/rat/proc scintFitter

/rat/proc outntuple
/rat/proclast outroot
##########EVENT LOOP############
/generator/add combo gun:fill:uniform
/generator/vtx/set e- 0 0 0 0.5
/generator/pos/set scint
/generator/rate/set 1

/rat/run/start
exit
